title       = "mogi"
baseURL     = "https://mogi-cli.tamnd.com/"
description = "A command line for mogi."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/mogi-cli"
